import type { Metadata } from "next";
import { Providers } from "./_components/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ padding: "4rem" }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
